### ISSUE TITLE
Github Icon is not visible in Dark mode

### ISSUE THREAD

**Issue by salmantec** [ashutosh1919/ashutosh1919#2]
## Description

Hi, I saw your github README.md (profile) which is really awesome. The one minor thing I want to share with you is, the Github logo is not visible in the profile page If I use dark mode. Here I have attached the screenshot for your reference. Could you please take a look.

<img width="1134" alt="Screenshot 2022-10-25 at 9 09 36 PM" src="https://user-images.githubusercontent.com/41512228/197820543-4c133a65-a477-43fd-82be-922d683105ba.png">

**Comment by ashutosh1919** [comment]
@salmantec That's the official GitHub logo. I don't think I can substitute an alternative logo for that. Please reopen issue if you think you have a solution for this. Thanks for suggestion anyways!
